### ISSUE TITLE
Error when running managed benchmarks in Docker image

### ISSUE THREAD

**Issue by guineveregilman** [DebashisGanguly/gpgpu-sim_UVMSmart#1]
After building the image from the Dockerfile, I am having trouble running the test cases provided in  benchmarks/Managed. Specifically, the backprop benchmark outputs "ALLOC_1D_DBL: Couldn't allocate array of n floats", indicating that the cudaMallocManaged calls returned null. Running some of the other benchmarks like sssp give an error saying that the CUDA driver version is insufficient for the runtime version. This is directly after having built the image, before making any modifications, aside from adding the CUDA installation to the path. What could be causing this?

**Comment by DebashisGanguly** [comment]
I am not sure what you meant by "CUDA installation to the path". Your host doesn't need any CUDA driver or runtime or even a physical GPU. 
Please start afresh and follow the steps once more meticulously without any changes and see if you can reproduce this issue.
It is impossible for me to comment on this issue without looking into the container itself.
Others are using the container without any issues so far. So, please be patient and give it a fresh try once more. If you are still facing issues then I will need more information from your side to investigate.

**Comment by guineveregilman** [comment]
Thank you for your response. When I originally build the image, the docker build command in the readme file outputs this error: "unknown shorthand flag: 'i' in -it". I could not find any information on the -i flag for the docker build command. If I build the image having omitted the -i flag, trying to run the benchmarks outputs: "error while loading shared libraries: libcudart.so.8.0: cannot open shared object file: No such file or directory", which I tried to fix like this:
`export LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64:$LD_LIBRARY_PATH`
And this is where I ended up with the above problems.

**Comment by DebashisGanguly** [comment]
Yeah, there are few typographical errors in the README which I need to take sometime to fix. One of such errors is -it option. It should be just -t.

You shouldn't be getting that error. I tried it again on a different server today and it just works fine.

Can you please try to execute the following set of commands manually and see if the errors are persisting? 

cd /root/gpgpu-sim_UVMSmart; source setup_environment; make -j20; cd benchmarks/; ./setup_config.sh GeForceGTX1080Ti; make; find . -name 'run' | xargs chmod +x

As I said, you do not need to set the library path yourself. Even that path you mentioned is wrong. It is the path of the host machine which we are not going to use for simulation. The simulator itself creates the libraries for you. The path to that libraries is set by setup_environment. 

Are you sure you are logging in to the right docker container and also executing the benchmarks from the container prompt and not the host command line? Please verify and make sure.

"sudo docker build -t UVMSmart:latest ." will build the image named UVMSmart:latest.

Then you need to create an instance of the image using sudo docker run --name <experiment_name> -it UVMSmart:latest. This is an interactive session and so -i option is must here. This will take you to the container command prompt.

Let me know for further issues.

**Comment by DebashisGanguly** [comment]
@guineveregilman Is this issue solved at your end or still open? Please let me know.

**Comment by guineveregilman** [comment]
I am sorry for the delay in my response. This was able to solve my problem. Thank you for your help!

**Comment by DebashisGanguly** [comment]
@guineveregilman No problem. I am glad that you could resolve the issue. Please let me know if you need any help with the research or anyway I can be of assistance.
