### ISSUE TITLE
cudaMallocManaged support

### ISSUE THREAD

**Issue by lineagech** [DebashisGanguly/gpgpu-sim_UVMSmart#3]
Can the simulator can support over-gpu-memory allocation using cudaMallocManaged? Supposed gpu memory is 4GB and I want to allocate 6GB on host first and then gpu accesses by on-demand paging and then have oversubscription. Since I found thatcudaMallocManaged in cuda_runtime_api.cc and then subsequent call of gpu_mallocmanaged seem to have a 4G size limit?

**Comment by DebashisGanguly** [comment]
Yes, it supports over-subscription.

If you have read the ISCA'19 paper, it is all about eviction which only kicks in under oversubscription.

You can control the memory size by configuring gddr_size parameter in the config file. For example, if your working set is 12MB and you want to simulate 25% oversubscription, then you need to set the gadder_size as 9.6MB. This will be equivalent to a gddr5 (device memory of 9.6MB) or in other words working set of 12MB is 9.6*125/100MB.

GPGPU_sim is cycle accurate. So, it inherently is slow compared to any event driven alternative. So, it is not advisable to play with working sets in GBs. It will take weeks to finish any over-subscription experiment with working set in GBs.

Typically follow the benchmarks/benchmark_workingset.txt for ideal runtime. I have carefully chosen them in such a way that they can finish in reasonable amount of time which is in a day or so.

Please let me know if this answers your question and if it does kindly close the issue.

**Comment by DebashisGanguly** [comment]
@lineagech Hi Chia-Hao, is there any update on this issue? Did my answer clarify your doubt?

If yes, please close the ticket or else please update me on the issue.
