### ISSUE TITLE
plan to merge to original GPGPU-sim repo?

### ISSUE THREAD

**Issue by gangmul12** [DebashisGanguly/gpgpu-sim_UVMSmart#4]
Hi
I think this repo is very useful to everybody using gpgpu-sim
do you have any plan to merge this repo with original one?

thanks

**Comment by DebashisGanguly** [comment]
Thanks for your kind words. Please follow, star, and fork the repo to increase it's visibility and share it with more people. Also let me know if any potential opportunities arise for collaborations.

Yes, we have reached out to the current maintainers of the original simulator to merge our contribution to the main stream.

**Comment by gangmul12** [comment]
Oh I see.
Thank you for your contribution for open source/architecture society!

thanks
