### ISSUE TITLE
Query in Eviction code

### ISSUE THREAD

**Issue by nifey** [DebashisGanguly/gpgpu-sim_UVMSmart#9]
https://github.com/DebashisGanguly/gpgpu-sim_UVMSmart/blob/bafab5d728a911d671833a5f843eeda783dab9ac/src/gpgpu-sim/gpu-sim.cc#L2302-L2311

In the part where the pages are evicted, there is this loop that checks if there are any RW pages and decides the latency type based on it. The code uses latency_type::PCIE_WRITE_BACK by default and switches to latency_type::INVALIDATE if there are any RW pages in the set of evicted pages.

Shouldn't it be the other way around? I would expect to use writeback latency only when there are modified pages that needs to be written back and invalidate latency when all the pages are clean.

**Comment by DebashisGanguly** [comment]
Sorry, I couldn't respond to your issue here because of some work related complications. I will take a look in details and get back to you. Please let me know if you are still stuck with this.

**Comment by nifey** [comment]
Hello Debashis,

I got confused with the usage of the RW field. I thought that RW being set to 1 indicates that the page is dirty. But I later realized that the RW field gets the value 1 if it is read-only, and 2 or 3 if it is dirty. So this issue is resolved now. I forgot to close the issue.

Thanks for sharing this simulator as open source. It's very helpful.
